version: "3.8"


services:
  db:
    image: postgres:13-alpine
    hostname: db
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - db

  app:
    build:
      context: ${app_ROOT:-.}
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ${app_ROOT:-.}:/opt/app
      - ~/.ipython:/root/ipython
    depends_on:
      - db
      - minio
    ports:
      - 8000:8000
    networks:
      - db
      - storage
      - webserver

  minio:
    image: minio/minio
    hostname: minio
    volumes:
      - minio_data:/var/data
    environment:
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
    ports:
      - 9000:9000
    command: server /var/data
    networks:
      - storage
      - webserver

  webserver:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    secrets:
      - nginx.crt
      - nginx.key
    networks:
      - webserver


secrets:
  nginx.crt:
    external: true
  nginx.key:
    external: true


volumes:
  dbdata:
  minio_data:


networks:
  db:
  storage:
  webserver:
