version: "3.7"


services:
  db:
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - db

  app:
    ports:
      - 8000:8000
    volumes:
      - ${APP_ROOT:-.}:/opt/app
      - ~/.ipython:/root/ipython
      - ~/.virtualenv/django-backend/lib/python3.8/site-packages:/usr/local/lib/python3.9/site-packages
    networks:
      - db
      - storage

  minio:
    environment:
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
    ports:
      - 9000:9000
    networks:
      - storage


volumes:
  dbdata:
  minio_data:


networks:
  db:
  storage:
