version: "3.7"


services:
  db:
    image: postgres:13-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  app:
    build:
      context: ${app_ROOT:-.}
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ${app_ROOT:-.}:/opt/app
      - ~/.ipython:/root/ipython
    depends_on:
      - db
    ports:
      - 8000:8000

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
    ports:
      - 9000:9000
    command: server data

volumes:
  dbdata:
  minio_data:
