version: "3.7"


services:
  db:
    image: postgres:13-alpine
    hostname: db
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - db


  app:
    build:
      context: ${APP_ROOT:-.}
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - minio
    networks:
      - db
      - storage


  minio:
    image: minio/minio
    hostname: minio
    volumes:
      - minio_data:/var/data
    command: server /var/data
    networks:
      - storage


volumes:
  dbdata:
  minio_data:


networks:
  db:
  storage:
