version: "3.7"


services:
  db:
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  app:
    ports:
      - 8000:8000

  minio:
    environment:
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
    ports:
      - 9000:9000


volumes:
  dbdata:
  minio_data:


networks:
  db:
  storage:
  webserver:
