version: "3.7"


services:
  db:
    image: postgres:13-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  app:
    build:
      context: ${app_ROOT:-.}
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ${app_ROOT:-.}:/opt/app
      - ~/.ipython:/root/ipython
    depends_on:
      - db
    ports:
      - "8000:8000"


volumes:
  dbdata:
