version: "3.7"


services:
  db:
    image: postgres:13-alpine
    hostname: db
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB_FILE: "/run/secrets/db-name"
      POSTGRES_USER_FILE: "/run/secrets/db-user"
      POSTGRES_PASSWORD_FILE: "/run/secrets/db-pass"
    secrets:
      - db-name
      - db-user
      - db-pass
    networks:
      - db
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
      resources:
        limits:
          cpus: '0.75'
          memory: 800M
        reservations:
          cpus: '0.1'
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 1s


  app:
    image: app
    build:
      context: ${APP_ROOT:-.}
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ${APP_ROOT:-.}:/opt/app
      - ~/.ipython:/root/ipython
    depends_on:
      - db
      - minio
    ports:
      - 8000:8000
    networks:
      - db
      - storage
      - webserver
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
      resources:
        limits:
          cpus: '0.9'
          memory: 700M
        reservations:
          cpus: '0.15'
          memory: 300M
      restart_policy:
        condition: on-failure
        delay: 1s
      update_config:
        order: start-first


  minio:
    image: minio/minio
    hostname: minio
    volumes:
      - minio_data:/var/data
    secrets:
      - secret_key
      - access_key
    ports:
      - 9000:9000
    command: server /var/data
    networks:
      - storage
      - webserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - "node.role==manager"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3


  webserver:
    image: webserver
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    secrets:
      - nginx.crt
      - nginx.key
    networks:
      - webserver
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.05'
          memory: 15M
      restart_policy:
        condition: on-failure
        delay: 1s
      update_config:
        order: start-first


secrets:
  nginx.crt:
    external: true
  nginx.key:
    external: true
  db-name:
    external: true
  db-user:
    external: true
  db-pass:
    external: true
  secret_key:
    external: true
  access_key:
    external: true


volumes:
  dbdata:
  minio_data:


networks:
  db:
  storage:
  webserver:
