version: "3.7"


services:
  db:
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  app:
    ports:
      - 8000:8000
    volumes:
      - ${APP_ROOT:-.}:/opt/app
      - ~/.ipython:/root/ipython
    command: >-
      gunicorn boilerplate.wsgi:application \
              --name boilerplate-gunicorn \
              --bind 0.0.0.0:8000 \
              --workers 10 \
              --pythonpath "/opt/app/src" \
              --log-level=debug \
              --timeout 120 \
              --reload

  minio:
    environment:
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
    ports:
      - 9000:9000


volumes:
  dbdata:
  minio_data:


networks:
  db:
  storage:
  webserver:
