version: "3.7"


services:
  db:
    image: postgres:13-alpine
    hostname: db
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - db


  app:
    image: django-backend_app
    build:
      context: ${APP_ROOT:-.}
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ${APP_ROOT:-.}:/opt/app
      - ~/.ipython:/root/ipython
    depends_on:
      - db
      - minio
    networks:
      - db
      - storage
      - webserver


  minio:
    image: minio/minio
    hostname: minio
    volumes:
      - minio_data:/var/data
    command: server /var/data
    networks:
      - storage
      - webserver


  webserver:
    image: django-backend_webserver
    build:
      context: nginx
      dockerfile: Dockerfile
    networks:
      - webserver


volumes:
  dbdata:
  minio_data:


networks:
  db:
  storage:
  webserver:
