version: "3.7"


services:
  db:
    image: postgres:13-alpine
    hostname: db
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - db


  app:
    image: django-backend_app
    build:
      context: ${APP_ROOT:-.}
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ${APP_ROOT:-.}:/opt/app
      - ~/.ipython:/root/ipython
    depends_on:
      - db
      - minio
    ports:
      - 8000:8000
    networks:
      - db
      - storage
      - webserver


  minio:
    image: minio/minio
    hostname: minio
    environment:
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
    volumes:
      - minio_data:/var/data
    ports:
      - 9000:9000
    command: server /var/data
    networks:
      - storage
      - webserver


  webserver:
    image: django-backend_webserver
    build:
      context: nginx
      dockerfile: Dockerfile
    networks:
      - webserver


volumes:
  dbdata:
  minio_data:


networks:
  db:
  storage:
  webserver:
